M48
; DRILL file {KiCad (7.0.0)} date Fri Mar 17 13:32:38 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-17T13:32:38-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X0.6693Y3.1063
X0.6693Y2.9488
T2
X0.8376Y3.8571
X1.0285Y3.8571
T3
X0.8258Y3.9764
X1.0404Y3.9764
T0
M30
